# Introduction

This notebook is to work on some basic concepts that lead up to the implementation of discrete explicit  solves.


In [1]:
import sys
import os
import time
import numpy as np
import matplotlib.pyplot as plt

# Add the directory containing your module to sys.path
module_path = os.path.abspath(os.path.join('..', r"A:\Users\mtthl\Documents\Education\ME5653_CFD\git\me5653_CFD_repo\code\lib" ))
sys.path.append(module_path)

from distributedObjects import *
from distributedFunctions import *


# FTCS

The forward in time, central in space (FTCS) method is the first method that we will use. First, let's check that the gradient is coming out the way we would expect it would.


In [2]:
gradient_a = numericalGradient( 2 , ( 1 , 1 ) )


In [3]:
gradient_a.coeffs


array([ 1., -2.,  1.])

In [4]:
gradient_a.coeffs_LHS


array([ 1., -2.,  1.])

In [5]:
gradient_a.coeffs_RHS


array([ 1., -2.,  1.])

Thus, the gradient looks how we would expect it to.


In [6]:
gradient_a.formMatrix(10)


In [7]:
gradient_a.gradientMatrix.toarray()


array([[ 1., -2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1., -2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1., -2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1., -2.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1., -2.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1., -2.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1., -2.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1., -2.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., -2.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., -2.,  1.]])

In [8]:
gradient_a.gradientMatrix + np.identity(10)


matrix([[ 2., -2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1., -1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1., -1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  1., -1.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1., -1.,  1.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  1., -1.,  1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  1., -1.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  1., -1.,  1.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., -1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., -2.,  2.]])

Thus, the matrix that is created by the gradient is how we would expect it to be.


In [9]:
L = 0.300 #[m]
T_0 = 100 #[K]
T_w = 300 #[K]
dx = 0.015 #[m]
alpha = 3e-6 #[m2/s]

x = np.arange( 0 , L+dx , dx )
T = T_0 * np.ones( len( x ) )
T[0] = T_w
T[-1]= T_w

heatEq_FTCS = heatEquation( x , T , ( 0 , 300 ) , alpha = alpha , S = 0.25 )

In [10]:
heatEq_FTCS.dx

np.float64(0.015000000000000003)

In [11]:
heatEq_FTCS.u

array([[300., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
        100., 100., 100., 100., 100., 100., 100., 100., 100., 300.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],

In [12]:
heatEq_FTCS.dt

np.float64(18.750000000000007)

In [13]:
heatEq_FTCS.solve()

In [14]:
heatEq_FTCS.u


array([[300.        , 100.        , 100.        , 100.        ,
        100.        , 100.        , 100.        , 100.        ,
        100.        , 100.        , 100.        , 100.        ,
        100.        , 100.        , 100.        , 100.        ,
        100.        , 100.        , 100.        , 100.        ,
        300.        ],
       [300.        , 150.        , 100.        , 100.        ,
        100.        , 100.        , 100.        , 100.        ,
        100.        , 100.        , 100.        , 100.        ,
        100.        , 100.        , 100.        , 100.        ,
        100.        , 100.        , 100.        , 150.        ,
        300.        ],
       [300.        , 175.        , 112.5       , 100.        ,
        100.        , 100.        , 100.        , 100.        ,
        100.        , 100.        , 100.        , 100.        ,
        100.        , 100.        , 100.        , 100.        ,
        100.        , 100.        , 112.5       , 175.    

In [15]:
np.shape( heatEq_FTCS.u )


(16, 21)

In [16]:
heatEq_FTCS.exact( 1000 )


In [17]:
heatEq_FTCS.u_exact


array([[ 3.00000000e+02,  1.00000000e+02,  1.00000000e+02,
         1.00000000e+02,  1.00000000e+02,  1.00000000e+02,
         1.00000000e+02,  1.00000000e+02,  1.00000000e+02,
         1.00000000e+02,  1.00000000e+02,  1.00000000e+02,
         1.00000000e+02,  1.00000000e+02,  1.00000000e+02,
         1.00000000e+02,  1.00000000e+02,  1.00000000e+02,
         1.00000000e+02,  1.00000000e+02,  3.00000000e+02],
       [ 3.00000000e+02, -1.70803172e+01, -5.81289060e+01,
        -3.99911638e+01, -1.99999938e+01,  6.14818418e-10,
         2.00000000e+01,  4.00000000e+01,  6.00000000e+01,
         8.00000000e+01,  1.00000000e+02,  1.20000000e+02,
         1.40000000e+02,  1.60000000e+02,  1.80000000e+02,
         2.00000000e+02,  2.20000000e+02,  2.40000000e+02,
         2.60000000e+02,  2.80000000e+02,  3.00000000e+02],
       [ 3.00000000e+02,  4.69242031e+01, -4.17998944e+01,
        -3.89200816e+01, -1.99746630e+01,  2.29321258e-04,
         2.00000008e+01,  4.00000000e+01,  6.00000000e